---
title: "Set up instructions for Excel output code (v1.0.0)"
author: "Izaak Jephson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Contents
 - `run.R` - Main script to be reviwed and edited for each publication.
 - `inputs/` - Contains `table_metadata.xlsx` file to be reviewed and edited for each publication. Also contains example input data `adp_2024_04.R` which is not needed for each publication.
 - `R` - Folder containing functions referenced by `run.R`. You should not need to edit these directly.
 - `outputs/` - Example output tables (not needed for each publication as this will be generated by code).

## Instructions for set up
 1. Copy contents of `R` folder into your publication project, into folder containing publication scripts. 
 2. Copy `table_metadata.xlsx` into your `inputs/` or `data/` folder. 
 3. Ensure your code produces your tables as a named list of data frames/tibbles. BY default this object should be called `data_tables`, though if multiple outputs are needed, then create multiple objects called e.g. `data_tables_raw`, `data_tables_rounded` etc. 
 4. Review and edit `table_metadata.xlsx`. The data fields to edit are as follows:
      - contents: contents_title - The title to be displayed on your contents page 
      - sheet_layout: sheet_number - ID column for sheets
      - sheet_layout: sheet_name - Name to be displayed on sheet tab and appear as a link on contents page
      - sheet_layout: sheet_title - Wording to appear as bold title at top of each sheet
      - sheet_layout: tables - List of tables to include on each sheet. Names should correspond to names in `data_tables`. If multiple tables on one page, then delimit with `,`, no space.
      - sheet_layout: notes - Notes to be included at bottom of sheet and attached to sheet title. Delimit with `,`, no space.
      - tables: table_name -  Names should correspond to names in `data_tables`.
      - tables: table_title - Title to be displayed directly above table. only needed if multiple tables on one sheet, otherwise leave as n/a.
      - notes: note_number - Number to be displayed wherever note is referenced. 
      - notes: note_text - Text corresponding to each note. Will be printed under each table where note applies.
      - options - In development. Turn on/off certain pages. Defaults should be fine for most publications.
 5. Review and edit `run.R` to point to correct files and data objects for your publication. This can be incorporated into your code at a sensible place or left as a standalone script to be called in your pipeline.
 
## Troubleshooting and suggestions
If you have any issues setting up this code, feel free to contact [Izaak Jephson](mailto:izaak.jephson@socialsecurity.gov.scot) for troubleshooting. If you have any feedback or suggestions for future versions, please get in touch!